### ISSUE TITLE
`make build` and `make test` fail due to an invalid module version

### ISSUE THREAD

**Issue by nao1215** [datachainlab/cross#70]
### Issue:

The cross framework is currently unable to run builds or tests due to an issue with `go.mod`. Below is the build log:

```shell
$ make build 
go build -o ./build/simd ./simapp/simd
go: github.com/cosmos/cosmos-sdk@v0.43.0-beta1 requires
        github.com/tendermint/cosmos-rosetta-gateway@v0.3.0-rc2.0.20210304154332-87d6ca4410df: invalid version: unknown revision 87d6ca4410df
make: *** [Makefile:3: build] Error 1
```

### Solution:

The solution would be to update the versions of `github.com/cosmos/cosmos-sdk` and `github.com/cosmos/ibc-go` to their latest releases.

The cross framework relies on outdated library versions across the board. I considered submitting a pull request to update the libraries, but to avoid any potential conflicts with the direction you may have in mind, I opted to open this issue instead.

### Alternative Solution

If you prefer not to update the libraries manually, I recommend using Dependabot for automated library updates. Below is an example configuration for .github/dependabot.yml:

```yaml
version: 2
updates:
  # Update go.mod
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "daily"
      time: "20:00"
    open-pull-requests-limit: 10

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```
